export const countries = [
  { code: 'AR', name: 'Argentina', prefix: '+54' },
  { code: 'BO', name: 'Bolivia', prefix: '+591' },
  { code: 'CL', name: 'Chile', prefix: '+56' },
  { code: 'CO', name: 'Colombia', prefix: '+57' },
  { code: 'CR', name: 'Costa Rica', prefix: '+506' },
  { code: 'CU', name: 'Cuba', prefix: '+53' },
  { code: 'EC', name: 'Ecuador', prefix: '+593' },
  { code: 'SV', name: 'El Salvador', prefix: '+503' },
  { code: 'ES', name: 'España', prefix: '+34' },
  { code: 'US', name: 'Estados Unidos', prefix: '+1' },
  { code: 'GT', name: 'Guatemala', prefix: '+502' },
  { code: 'HN', name: 'Honduras', prefix: '+504' },
  { code: 'MX', name: 'México', prefix: '+52' },
  { code: 'NI', name: 'Nicaragua', prefix: '+505' },
  { code: 'PA', name: 'Panamá', prefix: '+507' },
  { code: 'PY', name: 'Paraguay', prefix: '+595' },
  { code: 'PE', name: 'Perú', prefix: '+51' },
  { code: 'PR', name: 'Puerto Rico', prefix: '+1-787' },
  { code: 'DO', name: 'República Dominicana', prefix: '+1-809' },
  { code: 'UY', name: 'Uruguay', prefix: '+598' },
  { code: 'VE', name: 'Venezuela', prefix: '+58' },
];